// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pypaprint.pedidos.services;

import com.pypaprint.pedidos.domain.security.AuthorityPrincipalAssignment;
import com.pypaprint.pedidos.services.AuthorityPrincipalAssignmentService;
import java.util.List;

privileged aspect AuthorityPrincipalAssignmentService_Roo_Service {
    
    public abstract long AuthorityPrincipalAssignmentService.countAllAuthorityPrincipalAssignments();    
    public abstract void AuthorityPrincipalAssignmentService.deleteAuthorityPrincipalAssignment(AuthorityPrincipalAssignment authorityPrincipalAssignment);    
    public abstract AuthorityPrincipalAssignment AuthorityPrincipalAssignmentService.findAuthorityPrincipalAssignment(Long id);    
    public abstract List<AuthorityPrincipalAssignment> AuthorityPrincipalAssignmentService.findAllAuthorityPrincipalAssignments();    
    public abstract List<AuthorityPrincipalAssignment> AuthorityPrincipalAssignmentService.findAuthorityPrincipalAssignmentEntries(int firstResult, int maxResults);    
    public abstract void AuthorityPrincipalAssignmentService.saveAuthorityPrincipalAssignment(AuthorityPrincipalAssignment authorityPrincipalAssignment);    
    public abstract AuthorityPrincipalAssignment AuthorityPrincipalAssignmentService.updateAuthorityPrincipalAssignment(AuthorityPrincipalAssignment authorityPrincipalAssignment);    
}
