// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pypaprint.pedidos.services;

import com.pypaprint.pedidos.domain.security.AuthorityPrincipalAssignment;
import com.pypaprint.pedidos.services.AuthorityPrincipalAssignmentServiceImpl;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AuthorityPrincipalAssignmentServiceImpl_Roo_Service {
    
    declare @type: AuthorityPrincipalAssignmentServiceImpl: @Service;
    
    declare @type: AuthorityPrincipalAssignmentServiceImpl: @Transactional;
    
    public long AuthorityPrincipalAssignmentServiceImpl.countAllAuthorityPrincipalAssignments() {
        return AuthorityPrincipalAssignment.countAuthorityPrincipalAssignments();
    }
    
    public void AuthorityPrincipalAssignmentServiceImpl.deleteAuthorityPrincipalAssignment(AuthorityPrincipalAssignment authorityPrincipalAssignment) {
        authorityPrincipalAssignment.remove();
    }
    
    public AuthorityPrincipalAssignment AuthorityPrincipalAssignmentServiceImpl.findAuthorityPrincipalAssignment(Long id) {
        return AuthorityPrincipalAssignment.findAuthorityPrincipalAssignment(id);
    }
    
    public List<AuthorityPrincipalAssignment> AuthorityPrincipalAssignmentServiceImpl.findAllAuthorityPrincipalAssignments() {
        return AuthorityPrincipalAssignment.findAllAuthorityPrincipalAssignments();
    }
    
    public List<AuthorityPrincipalAssignment> AuthorityPrincipalAssignmentServiceImpl.findAuthorityPrincipalAssignmentEntries(int firstResult, int maxResults) {
        return AuthorityPrincipalAssignment.findAuthorityPrincipalAssignmentEntries(firstResult, maxResults);
    }
    
    public void AuthorityPrincipalAssignmentServiceImpl.saveAuthorityPrincipalAssignment(AuthorityPrincipalAssignment authorityPrincipalAssignment) {
        authorityPrincipalAssignment.persist();
    }
    
    public AuthorityPrincipalAssignment AuthorityPrincipalAssignmentServiceImpl.updateAuthorityPrincipalAssignment(AuthorityPrincipalAssignment authorityPrincipalAssignment) {
        return authorityPrincipalAssignment.merge();
    }
    
}
