// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pypaprint.pedidos.domain;

import com.pypaprint.pedidos.domain.PedidoProductos;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PedidoProductos_Roo_Configurable {
    
    declare @type: PedidoProductos: @Configurable;
    
}
