// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pypaprint.pedidos.domain;

import com.pypaprint.pedidos.domain.ProductoUpload;

privileged aspect ProductoUpload_Roo_JavaBean {
    
    public byte[] ProductoUpload.getFile() {
        return this.file;
    }
    
    public void ProductoUpload.setFile(byte[] file) {
        this.file = file;
    }
    
}
