// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pypaprint.pedidos.domain;

import com.pypaprint.pedidos.domain.StatusPedido;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect StatusPedido_Roo_Configurable {
    
    declare @type: StatusPedido: @Configurable;
    
}
